import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BackgroundBeams } from "@/components/ui/background-beams";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { setTheme } = useTheme();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen  bg-neutral-950  relative antialiased">
          <div className="h-full w-full p-4 relative z-10 ">{children}</div>
          <BackgroundBeams />
        </div>
      </body>
    </html>
  );
}
